#!/bin/bash

echo "🚀 Madison Vet Finder - GitHub Push Script"
echo "=========================================="
echo ""
echo "Before running this script, you need to:"
echo "1. Create a new repository on GitHub: https://github.com/new"
echo "2. Name it: madison-vet-finder"
echo "3. Keep it Private (recommended)"
echo "4. DO NOT initialize with README"
echo ""
echo "Then run these commands:"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/madison-vet-finder.git"
echo "git push -u origin main"
echo ""
echo "Replace YOUR_USERNAME with your actual GitHub username"
echo ""
echo "After pushing, go to Vercel.com to deploy!"
